[package]
name = "zisk_solana_prover"
version = "0.1.0"
edition = "2021"

[dependencies]
ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git" }
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

[profile.release]
panic = "abort"
